# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=dbg
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),dbg)
  interact_config = dbg
  rlearray_config = dbg
  test_config = dbg
  clobber_config = dbg
endif
ifeq ($(config),dist)
  interact_config = dist
  rlearray_config = dist
  test_config = dist
  clobber_config = dist
endif

PROJECTS := interact rlearray test clobber

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

interact: rlearray
ifneq (,$(interact_config))
	@echo "==== Building interact ($(interact_config)) ===="
	@${MAKE} --no-print-directory -C . -f interact.make config=$(interact_config)
endif

rlearray:
ifneq (,$(rlearray_config))
	@echo "==== Building rlearray ($(rlearray_config)) ===="
	@${MAKE} --no-print-directory -C . -f rlearray.make config=$(rlearray_config)
endif

test: rlearray
ifneq (,$(test_config))
	@echo "==== Building test ($(test_config)) ===="
	@${MAKE} --no-print-directory -C . -f test.make config=$(test_config)
endif

clobber:
ifneq (,$(clobber_config))
	@echo "==== Building clobber ($(clobber_config)) ===="
	@${MAKE} --no-print-directory -C . -f clobber.make config=$(clobber_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f interact.make clean
	@${MAKE} --no-print-directory -C . -f rlearray.make clean
	@${MAKE} --no-print-directory -C . -f test.make clean
	@${MAKE} --no-print-directory -C . -f clobber.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  dbg"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   interact"
	@echo "   rlearray"
	@echo "   test"
	@echo "   clobber"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"